[package]
name = "slate-core"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
slate-hal = { version = "0.3.1", path = "../slate-hal" }
slate-erasure = { version = "0.3.1", path = "../slate-erasure" }
sha2 = { version = "0.11.0", default-features = false }
heapless = "0.8.0"

[features]
metrics = []
