[workspace]
members = [
    "crates/*",
    "fuzz",
]
exclude = [
    "targets/esp32",
    "bind",
]
resolver = "2"

[workspace.package]
version = "0.3.3"
edition = "2021"
description = "A secure, log-structured, authenticated, tamper-evident key-value engine for edge devices"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ja7ad/slate"
readme = "README.md"

[workspace.lints.clippy]
all = "deny"
