[package]
name = "slate-sim"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
slate-hal = { version = "0.1.0", path = "../slate-hal" }
rand = { version = "0.8", features = ["small_rng"] }
proptest = "1.5"
slate-core = { version = "0.1.0", path = "../slate-core" }
slate-crypto = { version = "0.1.0", path = "../slate-crypto" }
serde = { version = "1.0", features = ["derive"] }
