[package]
name = "slate-kv-crypto"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
chacha20poly1305 = { version = "0.11.0", default-features = false }
hkdf = { version = "0.13.0", default-features = false }
hmac = { version = "0.13.0", default-features = false }
sha2 = { version = "0.11.0", default-features = false }
slate-kv-core = { version = "0.3.2", path = "../slate-kv-core" }
zeroize = { version = "1.9.0", default-features = false, features = ["zeroize_derive"] }
